version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ./src/app/Dockerfile
    command: bash -c "python ./src/manage.py migrate &&  python ./src/manage.py runserver && python ./src/manage.py createsuperuser"
    volumes:
      - ./:/opt/app/
    networks:
    - testNet
    env_file:
      - ./src/app/.env
    ports:
      - 8000:8000
    depends_on:
      - "postgres"

  postgres:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=django
    networks:
    - testNet
    ports:
    - 5432:5432
    volumes:
    - postgres_data:/var/lib/postgresql/data/

networks:
  testNet:
    driver: bridge

volumes:
  postgres_data:    
